apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: noa
spec:
  selfSigned: { }

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: noa-selfsigned
spec:
  secretName: noa-tls
  privateKey:
    algorithm: ECDSA
    size: 521
    # TODO noa.noa.svc needs to be somehow dynamic
  dnsNames:
    - noa
    - noa.noa.svc
  issuerRef:
    name: noa
    kind: Issuer