apiVersion: v1
kind: Service
metadata:
  name: noa
  labels:
    app: noa
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: noa
