apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "noa.fullname" . }}
  labels:
  {{- include "noa.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "noa.fullname" . }}
webhooks:
  - name: webhook.noa.brumhard.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
        resources:
          - secrets
    admissionReviewVersions: [ "v1" ]
    failurePolicy: {{ .Values.failurePolicy }}
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "noa.fullname" . }}
        namespace: {{ .Release.Namespace | quote }}
        path: /mutate